environment: production
aws_region: ap-northeast-1
services:
  example-service-test-production-audit-mysql80:
    source_db_instance_identifier: example-service-test-production-audit-mysql80
    source_engine_version: "8.0"
    source_db_parameter_group_name: example-service-test-production-audit-mysql80-v1
    target_engine_version: 8.4.10
    target_db_instance_class: db.r6g.large
    target_db_parameter_group_name: example-service-test-production-audit-mysql84-v1
    target_parameter_group_template_path: examples/config-blue-green-generation/target-parameter-groups/example-service-test-production-audit-mysql84.yaml
    protection_snapshot_identifier: example-service-test-production-audit-mysql80-pre-bg
    final_snapshot_identifier: example-service-test-production-audit-mysql80-final
    schemas:
      - example_service_test_audit
    source_db_parameters:
      time_zone:
        value: Asia/Tokyo
        source: user
    mysql_verification:
      enabled: true
      auth_method: parameter_store
      parameter_name: /rds-bg-test/audit/mysql-password
      user_parameter_name: /rds-bg-test/audit/mysql-user
      ssl_ca: ""
      port: 3307
    actions:
      build: pending
      switchover: pending
      switchover_timeout: 300
      cleanup: pending
  example-service-test-production-mysql80:
    source_db_instance_identifier: example-service-test-production-mysql80
    source_engine_version: "8.0"
    source_db_parameter_group_name: example-service-test-production-mysql80-v1
    target_engine_version: 8.4.10
    target_db_instance_class: db.r6g.xlarge
    target_db_parameter_group_name: example-service-test-production-mysql84-v1
    target_parameter_group_template_path: examples/config-blue-green-generation/target-parameter-groups/example-service-test-production-mysql84.yaml
    protection_snapshot_identifier: example-service-test-production-mysql80-pre-bg
    final_snapshot_identifier: example-service-test-production-mysql80-final
    schemas:
      - example_service_test
    source_db_parameters:
      time_zone:
        value: UTC
        source: engine-default
    mysql_verification:
      enabled: true
      auth_method: parameter_store
      parameter_name: /rds-bg-test/mysql-password
      user_parameter_name: /rds-bg-test/mysql-user
      ssl_ca: ""
      port: 3306
    actions:
      build: pending
      switchover: pending
      switchover_timeout: 300
      cleanup: pending
