# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 3.4.0"

gem "aws-sdk-cloudformation", "~> 1.0"
gem "aws-sdk-ec2", "~> 1.0"
gem "aws-sdk-iam", "~> 1.0"
gem "aws-sdk-ssm", "~> 1.0"

group :development, :test do
  gem "rspec", "~> 3.13"
  gem "rubocop", "~> 1.0", require: false
end
