# frozen_string_literal: true

require "json"
require "optparse"
require "time"
require "yaml"

require "aws-sdk-cloudformation"
require "aws-sdk-ec2"
require "aws-sdk-iam"
require "aws-sdk-ssm"

require_relative "ami_publish/errors"
require_relative "ami_publish/configuration"
require_relative "ami_publish/structured_logger"
require_relative "ami_publish/aws_client_factory"
require_relative "ami_publish/poller"
require_relative "ami_publish/progress_logger"
require_relative "ami_publish/image_cleanup"
require_relative "ami_publish/stack_outputs"
require_relative "ami_publish/run_context"
require_relative "ami_publish/step_runner"
require_relative "ami_publish/steps/base_step"
require_relative "ami_publish/steps/check_instance_state"
require_relative "ami_publish/steps/check_release_instance_permissions"
require_relative "ami_publish/steps/create_image"
require_relative "ami_publish/steps/wait_image_available"
require_relative "ami_publish/steps/start_instance_if_stopped"
require_relative "ami_publish/steps/wait_instance_online"
require_relative "ami_publish/steps/health_check"
require_relative "ami_publish/steps/update_launch_template_stack"
require_relative "ami_publish/steps/publish_outputs"
require_relative "ami_publish/steps/find_published_image"
require_relative "ami_publish/commands/publish_command"
require_relative "ami_publish/commands/rollback_command"
require_relative "ami_publish/command_line_interface"
