source "https://rubygems.org"

gem "rails", "~> 7.2"
gem "puma", "~> 6.0"
gem "sprockets-rails"

group :development, :test do
  gem "rspec-rails", "~> 7.0"
end

group :test do
  gem "capybara", "~> 3.40"
  gem "selenium-webdriver", "~> 4.0"
end
